name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Publish .NET Core Project
        run: dotnet publish TupperBitmap.csproj -c Release -o release --nologo
      
      - name: Change base-tag in index.html from / to TupperBitmap
        run: sed -i 's/<base href="\/" \/>/<base href="\/TupperBitmap\/" \/>/g' release/wwwroot/index.html
    
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
        
      - name: Create a .nojekyll file
        run: touch release/wwwroot/.nojekyll
    
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
